version: "2"

services:
    async_consumer:
        build: cli
        working_dir: /application
        volumes:
            - ../..:/application
            - /var/log/application:/application/var/log
        command: php -d memory_limit=1000M
        restart: always
